name: Wrangler Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install frontend dependencies
        run: npm install
      - name: Run build command
        run: npm run build
      - name: CF Deploy
        uses: penalosa/conductor@master
        with:
          zone_id: ${{ secrets.zone_id }}
          api_key: ${{ secrets.api_key }}
          account_id: ${{ secrets.account_id }}
          email: ${{ secrets.email }}
          domain: dash.penalosa.dev
          bucket: ./build
